### ISSUE TITLE
지원 화면에 대한 개발 이슈를 정리한다.

### ISSUE THREAD

**Issue by devFancy** [woorifisa/apply#14]
프론트엔드, 백엔드 각각 개발 이슈를 아래 댓글(comment)로 정리한다.

개발 이슈는 **협업**해서 같이 진행한다.
  - 프론트엔드(윤서, 철철, 푸린)
  - 백엔드(팬시, 따시기)

**Comment by devFancy** [comment]
## 로그인

1. 카카오 소셜 로그인을 OIDC(3세대) JWT 토큰 형식으로 구현한다.
  - ID token으로 가져올 때 `이메일`만 가져오도록 구현한다.

## 지원자

1. 모집에 지원하는 지원자를 등록하는 기능을 구현한다.
  - 지원서(지원자IDX, 지원상태, 이름, 성별, 생년월일, 연락처, 학력)를 저장한다.

**Comment by purin48** [comment]
## 인적사항 작성 페이지

1. __지원자의 인적사항을 서버로 부터 가져온다.__
    - 인적사항이 있는 경우
        - 각각의 인적사항 정보를 입력 값에 넣어준다.
    - 인적사항이 없는 경우
        - 입력 값에 placeholder값을 보여준다.

<br/>

2. __인적사항 작성 폼을 구현한다.__
    - 이름 - (필수입력 / `input type = "text"`)
    - 성별 - (필수입력 / `input type= "radio"`)
    - 생년월일 - (필수입력 / `select`) | 생년월일 형식 참고 : ( https://codepen.io/jh91/pen/bGqRbWm )
        
    - 연락처 - (필수입력 / `input type="number"`**)**
    - 최종 학력 - (필수입력)
        - 최종학력 타입 고르기`input type=”radio”`
        - 학교명 `input type="text"`
        - 학과
            - ‘고졸’ 일 경우, 학과 텍스트 창 `disabled` 적용하기
    - 개인정보 동의서 - (필수입력 / `input type="checkbox"`)

<br/>

3. __입력 값에 대한 유효성 검사를 한다.__
    - 입력 값이 유효하지 않을 경우,
        - 붉은색 테두리로 입력 창 변경하기
        - 붉은색 글씨로 경고 메시지 보여주기
        - 입력 값을 입력하는 순간,
            - 검정색 테두리로 입력 창 변경하기
            - 경고 메시지 제거하기

<br/>

4. __‘초기화’ 버튼을 구현한다.__
    - 초기화 버튼 클릭 시,
        - 모달창 띄우기( Confirm창 )
            - 입력한 폼 내용 초기화

<br/>

5. __‘다음’ 버튼을 구현한다.__
    - 입력 값이 빈 값일 경우, 붉은색 테두리로 입력 창 변경하기
    - 유효성 검사를 마친 후, 다음 페이지(지원서 폼)로 이동한다.

**Comment by purin48** [comment]
## ( 공통 컴포넌트 ) 모달 창

1. 확인
    - 최종 제출하려 할 때

<br/>

2. 경고
    - 내가 다른클래스도 신청하려고 할 때
    - 로그인 안하고 지원하기 눌렀을 때
    - 지원서 작성 중 뒤로가기 할 때
    - 작성 중 새로고침 할 때

<br/>
