### ISSUE TITLE
논리적 ERD 설계를 만든다.

### ISSUE THREAD

**Issue by devFancy** [woorifisa/apply#17]
ERD 설계한 URL 👉🏻 [LucidChart](https://lucid.app/lucidchart/75e13647-7ccf-48f9-9e97-08826ed1bc16/edit?beaconFlowId=15D8C93EB519E0DE&invitationId=inv_60f2660d-5b8a-4c51-8539-ab1ea3ecd012&page=0_0#)

아래 내용을 참고하여 ERD 설계를 만든다.

### 지원자
- 지원하기
  - 개인정보 수집 및 이용 동의
  - 개인정보
    - 이름, 이메일, 성별, 생년월일, 연락처, 학력
  - 항목들
  - 지원서 작성 내용 사실 확인
  - 임시 저장
  - 자동 저장
- 나의 지원서
  - 지원서 수정
  - 이메일 찾기
  - 비밀번호 찾기
 
### 관리자
- 모집 관리
  - 모집명, 모집 기간, 모집 항목
- 지원 항목 관리
  - 지원자 정보
 
### 지원자
- 나의 지원서
  - 지원서 결과

### 관리자
- 선발 과정
  - 전체 지원자 - 엑셀 다운로드
  - 기초 CS 지식 평가
  - 면접 평가
- 평가 항목 관리
  - e.g. 서류, 기초 CS 지식
- 부정 행위자
- 메일 발송

## 참고 자료

클래스 다이어그램
- [UML: 클래스 다이어그램과 소스코드 매핑](https://www.nextree.co.kr/p6753/)
- [[UML] 클래스 다이어그램 작성법](https://gmlwjd9405.github.io/2018/07/04/class-diagram.html)

**Comment by xotlr333** [comment]
![erd_kong](https://github.com/woorifisa/apply/assets/81614820/7ad52d3d-83ef-4c03-897e-41f74107a2b4)

**Comment by han0224** [comment]
<img width="875" alt="스크린샷 2023-06-28 오후 5 40 32" src="https://github.com/woorifisa/apply/assets/70616579/e5b7fb40-411f-4426-96e8-b5627bdfacf3">

**Comment by purin48** [comment]
<img width="702" alt="erd_som" src="https://github.com/woorifisa/apply/assets/81960250/6c6842c0-39a3-45a8-b994-c0c365d2d9d2">

**Comment by Cheol-Cheol** [comment]
<img width="923" alt="erd-exercise" src="https://github.com/woorifisa/apply/assets/82077853/d3a1e78b-6266-4e2b-8a76-9dc961cbc18b">

**Comment by devFancy** [comment]
<img width="1000" alt="logical_erd" src="https://github.com/woorifisa/apply/assets/83820185/922538e1-85fa-4936-aa06-8b1a964aa032">
