### ISSUE TITLE
🤔 KPT 회고(Retrospection): Sprint 1~8 까지 진행한 결과

### ISSUE THREAD

**Issue by devFancy** [woorifisa/apply#73]
## 🤔 KPT 회고(Retrospection)
- `일시`: 2023-07-26 (목) 18시~20시(2H)
- `참석자`
  - 5명 (팬시, 윤서, 푸린, 따시기, 철철)
- `내용`: KPT 회고

### KPT (KEEP-PROBLEM-TRY) 방식
 
KPT는 애자일 운동의 창시자 중 한 명으로 알려진 미국의 프로그래머 알리스테어 콕크번에 의해 제안된 방법론입니다. 애자일이 전체적으로 프로젝트를 운영하는 방법론이라면, KPT는 프로젝트의 진행 단계에서 세부적인 액션을 시각적으로 분류하여 효과적으로 회고하고, 모든 구성원의 숙고가 반영된 개선안을 도출할 수 있는 방식입니다.

- `개발` 과 `협업`, 두 가지 키워드를 중심으로 각각의 KPT 회고를 작성해주세요~

```
KEEP : 좋았던 부분, 앞으로 계속 유지하고 싶은 방식
PROBLEM : 잘 되지 않았던 부분, 문제라고 생각하는 부분
TRY : PROBLEM을 해결할 수 있도록 실천해보고 싶은 솔루션
```

진행 방식에 대한 자세한 설명은 '[실수와 문제가 없는 스타트업은 없다](https://brunch.co.kr/@fromjayden/8)' 해당 글을 참고해주세요.

**Comment by devFancy** [comment]
## 개발

- Keep

- Problem

- Try

## 협업

- Keep

- Problem

- Try

**Comment by han0224** [comment]
## 개발
- Keep: 공통 컴포넌트를 먼저 제작해 이후 페이지를 구성할때 더욱 쉽게 구성할 수 있어 좋았다.
- Problem: 공통 컴포넌트를 만들때 정확한 요구사항을 정의하지 않아 이후 계속 수정하는 문제점이 발생했었다.
- Try: 공통 컴포넌트를 만들때 해당 컴포넌트에 필요한 속성이 무언인지 먼저 같이 정의하고 더욱 많은 기능을 구현하는 식으로 진행했으면 좋을 것 같다.

## 협업
- Keep: git을 체계적으로 사용하여 프로젝트 작업을 수월하게 할 수 있어 좋았고 앞으로도 이러한 체계로 프로젝트를 진행했으면 좋겠다.
- Problem: api명세서가 없어 데이터가 어떤형식으로 오는지 몰라 작업하기 어려웠다.
- Try: api에 대한 정보를 간단한 형식으로라도 공유를 하는 방향으로 작업을 했으면 좋을 것 같다.

**Comment by xotlr333** [comment]
## 개발

- Keep: OAuth 2.0, JWT를 이용한 인증/인가 부분을 경험할 수 있어서 좋았다.

- Problem: ERD 수정이 잦아서 개발하는 데, 엔티티부분을 계속 수정해야되서 번거로웠다.

- Try: 다음에는 ERD 구성을 좀 더 확실하게 하고, 각자 개발 들어가기 전에 엔티티를 먼저 생성한 후 개발을 들어가는 것이 좋을 것 같다.

## 협업

- Keep: git을 활용하여 애자일 방법론을 최대한 이용하려고 노력한 부분이 좋았다.

- Problem: api 명세서 없이 프로젝트를 진행하여 프론트와 작업하는데 어려움이 있었다.

- Try: api에 대한 정보를 확정이 아니더라도 명세서로 작성하여 프론트와 공유하면서 개발을 진행하면 좋을 것 같다.

**Comment by purin48** [comment]
## 협업

- KEEP
협업을 하면서, git을 다양하게 활용했던 부분이 좋았음
git wiki에서 회의를 기록했기 때문에 쉽게 참고할 수 있다는 부분도 좋았으며, git의 활용방법에 대해 다양하게 배워가는 것 같다.

- PROBLEM
초반에 기획 했던 프로젝트의 주제를 바꿨던 부분이 아쉬웠다.
하지만 주제 변경 후, 기획부터 신속하게 작업이 진행되어서 좋았다.

- TRY
요구사항을 명세화 할 때, 컴포넌트 명과 속성들을 자세히 정해두지 않은 점이 아쉬웠다.
다음 프로젝트에는 함께 정해보는 방식으로 구현해나갔으면 좋겠다.


## 개발
- KEEP
자주 사용되는 요소들을 공통 컴포넌트로 빼 놓은 부분이 활용성 측면에서 좋았던 것 같다.

- PROBLEM
vue에 대한 기초지식이 부족하여 마감기한을 못 지켰던 부분들이 아쉬웠다.

- TRY
vue에 대해 학습하고 익혀나가야겠다고 생각한다. 또한 JS도 꾸준히 공부하고 개발을 진행하면 좋을 것 같다.

**Comment by Cheol-Cheol** [comment]
## 개발

- Keep
이전에 프론트엔드 파트로 OAuth 소셜 로그인을 구현을 했던 경험이 있었는데. 백엔드 파트를 맡아서 내부적으로 OAuth 프로세스를 이해할 수 있었던 좋은 경험이 됐다. 해당 프로젝트에 참여했던 이유 중 하나가 교육 과정에서 배운 기술을 프로젝트에 적용함으로써 내 것으로 만들자 였다. 교육 과정 중에 배운 클라우드를 직접 RDS를 생성해 프로젝트에 적용하게 되어 단 기간에 이전보다 성장하게 되었다.

- Problem
경험이 적다보니 요구사항을 기반으로 ERD 설계에 있어서 어려움이 있었다. 

- Try
ERD의 부족한 지식을 채워나가 다음 프로젝트에는 원활하게 만들수 있도록 진행해보자.

## 협업

- Keep
각종 협업 툴을 경험해 협업 프로세스를 이해할 수 있었다. 이전에는 commit과 push만 했었지만, 체계적인 시스템 안에서 브랜치 전략부터 시작해서 기본적인 이슈 생성, PR까지 이번 프로젝트를 통해서 많은 경험을 하게 되었다.

- Problem
처음 협업 프로세스를 접하다보니, 협업 과정에서 중간중간 놓치는 부분이 있었다. 

- Try
깃, 깃헙 도구와 친해져서 체계적인 시스템을 스스로 설계할 수 있도록 성장하자.
